--liquibase formatted sql

--changeset MariusNMU:001-create-initial-schema splitStatements:true endDelimiter:;

CREATE TABLE site (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL,
    nom VARCHAR(100) NOT NULL,
    adresse VARCHAR(255) NOT NULL,
    actif BOOLEAN NOT NULL,
    CONSTRAINT uk_site_code UNIQUE (code)
);

CREATE TABLE terrain (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         site_id BIGINT NOT NULL,
                         numero VARCHAR(20) NOT NULL,
                         actif BOOLEAN NOT NULL,
                         CONSTRAINT uk_terrain_site_numero UNIQUE (site_id, numero),
                         CONSTRAINT fk_terrain_site FOREIGN KEY (site_id) REFERENCES site(id)
);

CREATE TABLE horaire_annuel_site (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     site_id BIGINT NOT NULL,
                                     annee_civile INT NOT NULL,
                                     heure_debut_reservation TIME NOT NULL,
                                     heure_fin_reservation TIME NOT NULL,
                                     CONSTRAINT uk_horaire_annuel_site_annee UNIQUE (site_id, annee_civile),
                                     CONSTRAINT fk_horaire_site FOREIGN KEY (site_id) REFERENCES site(id)
);

CREATE TABLE fermeture (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           date_fermeture DATE NOT NULL,
                           portee VARCHAR(20) NOT NULL,
                           motif VARCHAR(255),
                           site_id BIGINT,
                           CONSTRAINT fk_fermeture_site FOREIGN KEY (site_id) REFERENCES site(id),
                           CONSTRAINT ck_fermeture_portee_site CHECK (
                               (portee = 'GLOBALE' AND site_id IS NULL)
                                   OR
                               (portee = 'LOCALE' AND site_id IS NOT NULL)
                               )
);

CREATE TABLE membre (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        matricule VARCHAR(10) NOT NULL,
                        nom VARCHAR(100) NOT NULL,
                        prenom VARCHAR(100) NOT NULL,
                        categorie_membre VARCHAR(20) NOT NULL,
                        site_rattachement_id BIGINT,
                        actif BOOLEAN NOT NULL,
                        mot_de_passe_hash VARCHAR(255) NOT NULL,
                        solde_credit DECIMAL(10,2) NOT NULL,
                        CONSTRAINT uk_membre_matricule UNIQUE (matricule),
                        CONSTRAINT fk_membre_site_rattachement
                            FOREIGN KEY (site_rattachement_id) REFERENCES site(id)
);

CREATE TABLE administrateur (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                nom VARCHAR(100) NOT NULL,
                                prenom VARCHAR(100) NOT NULL,
                                email_ou_login VARCHAR(150) NOT NULL,
                                mot_de_passe_hash VARCHAR(255) NOT NULL,
                                role_administrateur VARCHAR(20) NOT NULL,
                                site_id BIGINT,
                                actif BOOLEAN NOT NULL,
                                CONSTRAINT uk_administrateur_email_ou_login UNIQUE (email_ou_login),
                                CONSTRAINT fk_administrateur_site FOREIGN KEY (site_id) REFERENCES site(id)
);

CREATE TABLE padel_match (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             terrain_id BIGINT NOT NULL,
                             date_heure_debut TIMESTAMP NOT NULL,
                             date_heure_fin TIMESTAMP NOT NULL,
                             mode_creation VARCHAR(20) NOT NULL,
                             visibilite_courante VARCHAR(20) NOT NULL,
                             prix_total DECIMAL(10, 2) NOT NULL,
                             date_creation TIMESTAMP NOT NULL,
                             date_passage_public TIMESTAMP,
                             etat_cycle VARCHAR(20) NOT NULL,
                             CONSTRAINT fk_match_terrain FOREIGN KEY (terrain_id) REFERENCES terrain(id)
);

CREATE TABLE participation (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               match_id BIGINT NOT NULL,
                               membre_id BIGINT NOT NULL,
                               role_participation VARCHAR(20) NOT NULL,
                               mode_entree VARCHAR(30) NOT NULL,
                               statut_participation VARCHAR(30) NOT NULL,
                               date_affectation TIMESTAMP NOT NULL,
                               date_confirmation TIMESTAMP,
                               date_liberation TIMESTAMP,
                               CONSTRAINT uk_participation_match_membre UNIQUE (match_id, membre_id),
                               CONSTRAINT fk_participation_match FOREIGN KEY (match_id) REFERENCES padel_match(id),
                               CONSTRAINT fk_participation_membre FOREIGN KEY (membre_id) REFERENCES membre(id)
);

CREATE TABLE dette (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       match_id BIGINT NOT NULL,
                       membre_responsable_id BIGINT NOT NULL,
                       montant_initial DECIMAL(10, 2) NOT NULL,
                       montant_restant DECIMAL(10, 2) NOT NULL,
                       date_creation TIMESTAMP NOT NULL,
                       date_reglement TIMESTAMP,
                       statut_dette VARCHAR(20) NOT NULL,
                       CONSTRAINT uk_dette_match UNIQUE (match_id),
                       CONSTRAINT fk_dette_match FOREIGN KEY (match_id) REFERENCES padel_match(id),
                       CONSTRAINT fk_dette_membre_responsable FOREIGN KEY (membre_responsable_id) REFERENCES membre(id)
);

CREATE TABLE penalite (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          membre_id BIGINT NOT NULL,
                          match_source_id BIGINT NOT NULL,
                          type_penalite VARCHAR(50) NOT NULL,
                          motif VARCHAR(255) NOT NULL,
                          date_debut TIMESTAMP NOT NULL,
                          date_fin TIMESTAMP NOT NULL,
                          statut_penalite VARCHAR(20) NOT NULL,
                          CONSTRAINT fk_penalite_membre FOREIGN KEY (membre_id) REFERENCES membre(id),
                          CONSTRAINT fk_penalite_match_source FOREIGN KEY (match_source_id) REFERENCES padel_match(id)
);

CREATE TABLE paiement (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          membre_id BIGINT NOT NULL,
                          nature_paiement VARCHAR(30) NOT NULL,
                          montant DECIMAL(10, 2) NOT NULL,
                          date_heure_paiement TIMESTAMP NOT NULL,
                          statut_paiement VARCHAR(20) NOT NULL,
                          participation_id BIGINT,
                          dette_id BIGINT,
                          CONSTRAINT uk_paiement_participation UNIQUE (participation_id),
                          CONSTRAINT uk_paiement_dette UNIQUE (dette_id),
                          CONSTRAINT fk_paiement_membre FOREIGN KEY (membre_id) REFERENCES membre(id),
                          CONSTRAINT fk_paiement_participation FOREIGN KEY (participation_id) REFERENCES participation(id),
                          CONSTRAINT fk_paiement_dette FOREIGN KEY (dette_id) REFERENCES dette(id),
                          CONSTRAINT ck_paiement_cible CHECK (
                              (participation_id IS NOT NULL AND dette_id IS NULL)
                                  OR
                              (participation_id IS NULL AND dette_id IS NOT NULL)
                              )
);

--rollback DROP TABLE paiement;
--rollback DROP TABLE penalite;
--rollback DROP TABLE dette;
--rollback DROP TABLE participation;
--rollback DROP TABLE padel_match;
--rollback DROP TABLE administrateur;
--rollback DROP TABLE membre;
--rollback DROP TABLE fermeture;
--rollback DROP TABLE horaire_annuel_site;
--rollback DROP TABLE terrain;
--rollback DROP TABLE site;
