# ==========================================================
# Profil PostgreSQL
# Activé uniquement avec :
# .\mvnw.cmd spring-boot:run -Dspring-boot.run.profiles=postgres
# ==========================================================

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/padel_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:padel_app}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:padel_app_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# MVP simple :
# Hibernate crée/met à jour les tables dans PostgreSQL à partir des entités JPA.
# H2 reste inchangé car ce fichier n'est lu que si le profil postgres est actif.
spring.jpa.hibernate.ddl-auto=update

# Utile en développement pour voir les requêtes SQL.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# On désactive la console H2 quand PostgreSQL est utilisé.
spring.h2.console.enabled=false

# Important :
# On évite d'exécuter automatiquement data.sql sur PostgreSQL,
# car le seed H2 peut contenir des syntaxes spécifiques à H2.
spring.sql.init.mode=never